import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const onboarding = JSON.parse(readFileSync('config/onboarding.json', 'utf8'))

const loadOptional = (path, fallback) => {
  try { return JSON.parse(readFileSync(path, 'utf8')) } catch { return fallback }
}
// Seeded, regenerated by scripts/generate-family-media.ts. Read only: the agent
// never sees these unless a member forwards one.
const familyHistory = loadOptional('config/family-history.json', { chats: [] })
const rpHistory = loadOptional('config/rp-history.json', { messages: [] })
// Sample trigger sentences offered in the UI. Static: only the sentence is ever
// sent to the agent, never the tier it is expected to land on.
const triggerSamples = loadOptional('config/trigger-samples.json', { samples: [] })

export const session = {
  startedAt: new Date().toISOString(),
  onboarding,
  clock: new Date(onboarding.sim_clock.start),
  stage: 1,
  model: `${process.env.MODEL_PROVIDER || 'gemini'} / ${process.env.MODEL_NAME || 'unset'}`,
  wallet: {
    limit: onboarding.wallet.limit_inr,
    spent: onboarding.wallet.spent_inr,
    ledger: [],
  },
  decisions: [],   // the competition's Part 1 table
  events: [],      // everything, replayed to a client that joins late
  messages: { patient: [], rp: [], family_group: [], doctor: [] },
  chats: {},       // live family-chat messages, keyed by chatKey() below
  chain: null,     // the current walk down the call chain, see contacts.js
  accounts: [],    // transcripts and summaries, see accounts.js
  assessments: [], // tiers and the factors behind them, see assessment.js
  reversals: [],   // decisions the RP may still overrule, see assessment.js
  ladders: {},     // how far down each ranked provider list we are, see acting.js
  providerLog: [], // every provider attempt and what came of it
  fulfilments: [], // what the chemist actually supplied
  deadEnds: [],    // exhausted lists, reported rather than passed over
  dispatches: [],  // emergency dispatches, all four parts present
  refillCycles: [],// run-out dates, set from what was dispensed (see acting.js)
  familyHistory,
  rpHistory,
  triggerSamples,
  history: [],     // provider-agnostic conversation history
  pending: [],     // curtain calls waiting on a teammate
}

const GROUP_CHATS = new Set((familyHistory.chats || []).filter((c) => c.kind === 'group').map((c) => c.id))

/**
 * Where a live chat message is stored.
 *
 * The seeded direct chats are each written from one viewpoint: the thread named
 * "Demo Patient" and the thread named "Demo RP" are two records of the same
 * pair, kept as they were recorded. Live messages instead hang off the pair
 * itself, so a line typed on one handset shows up on the other one. A group
 * keeps its own id, because everyone is already looking at the same thread.
 */
export function chatKey(from, chatId) {
  if (GROUP_CHATS.has(chatId)) return chatId
  return ['dm', ...[from, chatId].sort()].join(':')
}

const clients = new Set()

export function addClient(res, syncState) {
  clients.add(res)
  // Replay so a reconnect mid-take does not lose the recording.
  for (const e of session.events) write(res, e)

  // The replay above re-applies every historical `input` and `thinking`. If a
  // run ended without a terminal event in the log, a client that joins later
  // reduces its way to "working on it" and stays there for good. This says what
  // is true right now, and is deliberately not appended to session.events: it
  // is addressed to this one client at this one moment.
  if (syncState) write(res, { type: 'sync', at: new Date().toISOString(), clock: session.clock.toISOString(), ...syncState() })

  res.on('close', () => clients.delete(res))
}

function write(res, event) {
  res.write(`data: ${JSON.stringify(event)}\n\n`)
}

let snapshotTimer = null

export function emit(type, payload = {}) {
  const event = { type, at: new Date().toISOString(), clock: session.clock.toISOString(), ...payload }
  session.events.push(event)
  for (const res of clients) write(res, event)

  // ponytail: debounced whole-file snapshot. Session is a few hundred KB at
  // most and this only has to survive one crash during one take.
  clearTimeout(snapshotTimer)
  snapshotTimer = setTimeout(snapshot, 400)
  return event
}

/**
 * Back to a fresh take.
 *
 * Onboarding is re-read from disk rather than reused, because the agent edits
 * it as it goes: record_update changes schedules and set_refill_cycle writes
 * pills_left and the run-out date. Keeping the object would carry the last
 * run's edits into the next one, which is the kind of thing that only shows up
 * halfway through a recording.
 *
 * The event log is emptied before the reset event is emitted, so a client that
 * connects afterwards replays one event and lands on an empty session, while
 * clients already connected are told to clear.
 */
export function resetSession(reason = 'operator reset') {
  const fresh = JSON.parse(readFileSync('config/onboarding.json', 'utf8'))

  session.onboarding = fresh
  // Re-read from disk too, so an edited sample list lands without a restart.
  session.triggerSamples = loadOptional('config/trigger-samples.json', { samples: [] })
  session.clock = new Date(fresh.sim_clock.start)
  session.stage = 1
  session.startedAt = new Date().toISOString()
  session.wallet = { limit: fresh.wallet.limit_inr, spent: fresh.wallet.spent_inr, ledger: [] }
  session.decisions = []
  session.messages = { patient: [], rp: [], family_group: [], doctor: [] }
  session.chats = {}
  session.chain = null
  session.accounts = []
  session.assessments = []
  session.reversals = []
  session.ladders = {}
  session.providerLog = []
  session.fulfilments = []
  session.deadEnds = []
  session.dispatches = []
  session.refillCycles = []
  session.history = []
  session.pending = []
  session.tier = undefined
  session.events = []

  emit('reset', { reason, clock: session.clock.toISOString() })
  return { ok: true, reason, clock: session.clock.toISOString(), stage: session.stage }
}

export function snapshot() {
  try {
    mkdirSync('data', { recursive: true })
    writeFileSync('data/session.json', JSON.stringify(session, null, 2))
  } catch (err) {
    console.error('snapshot failed:', err.message)
  }
}

export function advanceClock(iso, source) {
  session.clock = new Date(iso)
  emit('clock', { clock: session.clock.toISOString(), source })
}

/** Uploaded audio, kept out of `session` so buffers never hit the JSON snapshot. */
export const audioStore = new Map()
